apiVersion: v1
kind: Template
metadata:
  name: alertmanager
  annotations:
    "openshift.io/display-name": Prometheus Alert Manager
    description: |
      A monitoring solution for an OpenShift cluster - collect and gather metrics from nodes, services, and the infrastructure. This component provides the Alert Manager.
    iconClass: icon-cogs
    tags: "monitoring,prometheus,alertmanager,time-series"
parameters:
- description: The location of the prometheus image
  name: IMAGE_ALERTMANAGER
  value: wkulhanek/alertmanager:latest
- name: VOLUME_CAPACITY
  displayName: Volume Capacity
  description: Volume space available for data, e.g. 512Mi, 2Gi.
  value: 4Gi
  required: true
objects:

- apiVersion: v1
  kind: Route
  metadata:
    name: alertmanager
  spec:
    to:
      name: alertmanager

- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      prometheus.io/scrape: "true"
    labels:
      name: alertmanager
    name: alertmanager
  spec:
    ports:
    - name: alertmanager
      port: 9093
      protocol: TCP
      targetPort: 9093
    selector:
      app: alertmanager

# Deploy Prometheus
- apiVersion: extensions/v1beta1
  kind: Deployment
  metadata:
    labels:
      app: alertmanager
    name: alertmanager
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: alertmanager
    template:
      metadata:
        labels:
          app: alertmanager
        name: alertmanager
      spec:
        containers:
        - name: alertmanager
          args:
          - -config.file=/etc/alertmanager/config.yml
          - -storage.path=/alertmanager
          image: ${IMAGE_ALERTMANAGER}
          imagePullPolicy: IfNotPresent
          volumeMounts:
          # - mountPath: /etc/alertmanager
          #   name: config-volume
          - mountPath: /alertmanager
            name: data-volume
        restartPolicy: Always
        volumes:
        - name: data-volume
          persistentVolumeClaim:
            claimName: alertmanager-data-pvc
        # - emptyDir: {}
        #   name: config-volume

- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: alertmanager-data-pvc
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: "${VOLUME_CAPACITY}"
