---
- hosts: localhost
  tasks:
  - name: Download latest node_exporter binary
    get_url:
      url: https://github.com/prometheus/node_exporter/releases/download/v0.14.0/node_exporter-0.14.0.linux-amd64.tar.gz
      dest: /tmp/node_exporter.tgz
  - name: Untar node_exporter binary
    unarchive:
      src: /tmp/node_exporter.tgz
      dest: /tmp
      copy: no
- hosts: nodes
  remote_user: ec2_user
  become: yes
  become_user: root
  tasks:
  - name: Copy node-exporter binary to node
    copy:
      src:   /tmp/node_exporter-0.14.0.linux-amd64/node_exporter
      dest:  /usr/local/bin/node_exporter
      owner: root
      group: root
      mode:  0755
  - name: Set up Service for node-exporter
    copy:
      src:   node_exporter.conf
      dest:  /etc/systemd/system/node_exporter.service
      owner: root
      group: root
      mode:  0644
  - name: Start node_exporter service on node
    systemd:
      name: node_exporter
      enabled: yes
      state: started
      daemon_reload: yes
  - name: Make sure firewall has open port 9100
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertafter: '-A FORWARD -j REJECT --reject-with icmp-host-prohibited'
      line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT'
      state: present
  - name: Restart IP Tables service
    systemd:
      name: iptables
      state: restarted
      daemon_reload: yes

# Clean up on Localhost
# Delete the downloaded and unarchived files
- hosts: localhost
  tasks:
  - name: Cleanup localhost /tmp
    file:
      path: /tmp/node_exporter.tgz
      state: absent
  - name: Cleanup localhost unarchived directory
    file:
      path: /tmp/node_exporter-0.14.0.linux-amd64
      state: absent
