---
- hosts: nodes
  remote_user: ec2_user
  become: yes
  become_user: root
  tasks:
  - name: Make sure firewall has open port 9100
    lineinfile:
      dest: /etc/sysconfig/iptables
      insertafter: '-A FORWARD -j REJECT --reject-with icmp-host-prohibited'
      line: '-A OS_FIREWALL_ALLOW -p tcp -m state --state NEW -m tcp --dport 9100 -j ACCEPT'
      state: present
  - name: Restart IP Tables service
    systemd:
      name: iptables
      state: restarted
      daemon_reload: yes
